field: 08cbe854-430a-4209-a87d-cc863f659182 # Page Blocks
fieldLayouts:
  05b520b0-56d6-4790-9d7f-5563206262dc:
    tabs:
      -
        elements:
          -
            fieldUid: bfdd02cc-136a-4223-a7bf-3fdb3d3100f9 # Size
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 4c28f35c-aa7b-4cc5-9714-00599869ae27 # Body
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  4c28f35c-aa7b-4cc5-9714-00599869ae27: # Body
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: body
    instructions: ''
    name: Body
    searchable: true
    settings:
      availableTransforms: '*'
      availableVolumes: '*'
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: ''
      purifyHtml: '1'
      redactorConfig: ''
      removeEmptyTags: '1'
      removeInlineStyles: '1'
      removeNbsp: '1'
      showHtmlButtonForNonAdmins: ''
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
  bfdd02cc-136a-4223-a7bf-3fdb3d3100f9: # Size
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: size
    instructions: ''
    name: Size
    searchable: false
    settings:
      optgroups: true
      options:
        -
          __assoc__:
            -
              - label
              - 'Half Width'
            -
              - value
              - halfWidth
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'Full Width'
            -
              - value
              - fullWidth
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
handle: text
name: Text
sortOrder: 1
