fieldLayouts:
  e9a3b412-8189-4f29-a29f-3b507706b8bb:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 1e4df4e8-5260-4752-a91d-a3637c8f63cc
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: a8e71ee5-274e-4e21-9156-dcd951e10739 # Body
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9ac0fbe0-8244-4974-82d0-624a29811c61
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: ce9ca5a9-7ec2-405f-a639-ab22bca77b92 # Link Blocks
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 25c0236f-761d-4101-8f32-8a1e71559fb9
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: e57891ce-fd3c-4d21-8300-dcf2270fa1d7
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 4f7f4cc2-cc21-4b6e-80ac-478cb881b9fb # SEO Description
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4b0cac77-e9ef-496f-b6fa-830daf5e2131
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: cbceb58e-c647-45ab-afbd-6c28b7dc9087 # SEO Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: eaa048fd-a30c-4f68-9cb3-7a7c9793fa4b
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 2646aee3-6b1a-45ae-94dd-c254b55fc84b # SEO Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b0a7dfed-bd8a-450e-9536-60e72358ba56
            userCondition: null
            warning: null
            width: 100
        name: SEO
        uid: d1c15b7f-d8da-4d01-b463-d595103ddf6c
        userCondition: null
handle: comicsIndex
hasTitleField: true
name: 'Comics Index'
section: ab89bd20-d119-4ac0-92b5-6ecdedb392fc # Comics Index
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
