fieldLayouts:
  703f03ae-301b-49e4-91bd-dd443c7a5355:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 71a99078-e1c7-4fa3-8772-42a2be3ffc1d
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: a8e71ee5-274e-4e21-9156-dcd951e10739 # Body
            instructions: 'Optional text at top of page'
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4f7ac255-40c5-4986-a162-ccf01e7a6aba
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: ce9ca5a9-7ec2-405f-a639-ab22bca77b92 # Link Blocks
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e80d9f25-e26b-407f-aeee-9f924855c7a0
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: df77656f-c134-4090-b73b-e55077cfb56f
        userCondition: null
handle: linksIndex
hasTitleField: true
name: 'Links Index'
section: 0d137df9-8ee2-467d-a261-d5090d788157 # Links Index
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
