fieldLayouts:
  ab155a32-5002-484e-b57b-c36322730517:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\EntryTitleField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
      -
        elements:
          -
            fieldUid: 4f7f4cc2-cc21-4b6e-80ac-478cb881b9fb # SEO Description
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: cbceb58e-c647-45ab-afbd-6c28b7dc9087 # SEO Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 2646aee3-6b1a-45ae-94dd-c254b55fc84b # SEO Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: SEO
        sortOrder: 2
handle: newsIndex
hasTitleField: true
name: 'News Index'
section: 4c74e475-0c0e-43c4-83d8-a70c025fd02b # News Index
sortOrder: 1
titleFormat: News
titleTranslationKeyFormat: null
titleTranslationMethod: site
