fieldLayouts:
  889256bc-9b2e-4692-8888-a0587e3aa595:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 0751e305-b7ff-4009-afb9-e215821133f7
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: a8e71ee5-274e-4e21-9156-dcd951e10739 # Body
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5bb63006-2f38-492b-9f65-917e273551a5
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 326ef589-65c7-4321-84e4-a59613583b53
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 4f7f4cc2-cc21-4b6e-80ac-478cb881b9fb # SEO Description
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: abcbf9a1-5616-40c3-9f8c-cbf206233aea
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: cbceb58e-c647-45ab-afbd-6c28b7dc9087 # SEO Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e4a22dd4-98e9-448f-ae72-f7e51efdf858
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 2646aee3-6b1a-45ae-94dd-c254b55fc84b # SEO Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1e073999-c067-4c12-abbc-034bee94e29f
            userCondition: null
            warning: null
            width: 100
        name: SEO
        uid: 6417e775-6371-4991-9b76-3f62b1ce5d4e
        userCondition: null
handle: post
hasTitleField: true
name: Post
section: c058c732-53bd-4770-adf6-542237db08c8 # News
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
