baseUrl: $PRIMARY_SITE_URL
enabled: true
handle: default
hasUrls: true
language: en-US
name: 'Alec Longstreth'
primary: true
siteGroup: 24430226-c637-40ff-91c3-963952acebcb # Alec Longstreth
sortOrder: 1
