fieldLayouts:
  077c5938-8602-4f3b-a250-d098b650c7d8:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 4aacea15-f9fd-4204-b06d-2120618200e6
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 5a79008a-7596-49f6-a308-ea896bf59465
        userCondition: null
fs: comics
handle: comics
name: Comics
sortOrder: 3
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: null
transformSubpath: ''
