fieldLayouts:
  4ece62d0-9f9d-44d7-8da3-8258fef79ddc:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 5d7c2151-e453-4617-a701-8d9c19f89c2c
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 2900a28f-afc9-46ef-ab64-b165e81e8f67
        userCondition: null
fs: general
handle: general
name: General
sortOrder: 1
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: null
transformSubpath: ''
