fieldLayouts:
  d37bf652-9f63-4137-9fc4-1376f568dfaf:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 04ee2c29-5a65-4a7b-8fc0-388b08dde52e
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 75afc8fd-054c-4a15-a7e3-4a53ec185dc5
        userCondition: null
fs: news
handle: news
name: News
sortOrder: 2
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: null
transformSubpath: ''
