columnSuffix: hikiawuu
contentColumnType: string
fieldGroup: 015d48f9-dd42-4c18-b3b5-8a8f4e9106e9 # Common
handle: bibliography
instructions: null
name: Bibliography
searchable: false
settings:
  blockTypeFields: 0
  changedFieldIndicator: null
  columns:
    __assoc__:
      -
        - 4c57db8a-2a37-4bf4-8636-62780119f7c0 # Title
        -
          __assoc__:
            -
              - width
              - ''
      -
        - c5367f71-b0ec-4e4d-8813-02ce06fed536 # Release Date
        -
          __assoc__:
            -
              - width
              - ''
      -
        - f149d6a3-c80e-45dc-a138-3ad98d2f5291 # Number of Pages
        -
          __assoc__:
            -
              - width
              - ''
      -
        - 7d2158f0-f36b-4144-b226-3f765ee39d98 # Anthology / Publisher
        -
          __assoc__:
            -
              - width
              - ''
  contentTable: '{{%stc_bibliography}}'
  fieldLayout: table
  maxRows: null
  minRows: null
  propagationKeyFormat: null
  propagationMethod: all
  selectionLabel: null
  staticField: null
translationKeyFormat: null
translationMethod: site
type: verbb\supertable\fields\SuperTableField
