columnSuffix: hikiawuu
contentColumnType: text
fieldGroup: 015d48f9-dd42-4c18-b3b5-8a8f4e9106e9 # Common
handle: bibliographyTable
instructions: ''
name: 'Bibliography Table'
searchable: false
settings:
  addRowLabel: 'Add a row'
  columnType: text
  columns:
    __assoc__:
      -
        - col1
        -
          __assoc__:
            -
              - heading
              - Title
            -
              - handle
              - title
            -
              - width
              - ''
            -
              - type
              - singleline
      -
        - col2
        -
          __assoc__:
            -
              - heading
              - 'Release Date'
            -
              - handle
              - releaseDate
            -
              - width
              - ''
            -
              - type
              - singleline
      -
        - col3
        -
          __assoc__:
            -
              - heading
              - '# of Pages'
            -
              - handle
              - ofPages
            -
              - width
              - ''
            -
              - type
              - singleline
      -
        - col4
        -
          __assoc__:
            -
              - heading
              - 'Anthology / Publisher'
            -
              - handle
              - anthologyPublisher
            -
              - width
              - ''
            -
              - type
              - singleline
  defaults:
    -
      __assoc__:
        -
          - col1
          - ''
        -
          - col2
          - ''
        -
          - col3
          - ''
        -
          - col4
          - ''
  maxRows: ''
  minRows: ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Table
