columnSuffix: pqelhheu
contentColumnType: text
fieldGroup: 015d48f9-dd42-4c18-b3b5-8a8f4e9106e9 # Common
handle: body
instructions: null
name: Body
searchable: true
settings:
  availableTransforms: '*'
  availableVolumes: '*'
  columnType: text
  configSelectionMode: choose
  defaultTransform: ''
  manualConfig: ''
  purifierConfig: null
  purifyHtml: false
  redactorConfig: null
  removeEmptyTags: true
  removeInlineStyles: false
  removeNbsp: true
  showHtmlButtonForNonAdmins: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  uiMode: enlarged
translationKeyFormat: null
translationMethod: none
type: craft\redactor\Field
