columnSuffix: null
contentColumnType: string
fieldGroup: 790b8232-1c19-47f1-9eda-8ab4993c0f3f # Comics
handle: comicImages
instructions: null
name: 'Comic Images'
searchable: false
settings:
  allowSelfRelations: false
  allowSubfolders: false
  allowUploads: true
  allowedKinds:
    - image
  branchLimit: null
  defaultUploadLocationSource: 'volume:7b466644-d7d2-4ddc-bb1c-42e5bab64ec0' # Comics
  defaultUploadLocationSubpath: '{slug}'
  localizeRelations: false
  maintainHierarchy: false
  maxRelations: null
  minRelations: null
  previewMode: full
  restrictFiles: true
  restrictLocation: false
  restrictedDefaultUploadSubpath: null
  restrictedLocationSource: 'volume:7b466644-d7d2-4ddc-bb1c-42e5bab64ec0' # Comics
  restrictedLocationSubpath: '{slug}'
  selectionLabel: 'Add images'
  showSiteMenu: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  sources:
    - 'volume:7b466644-d7d2-4ddc-bb1c-42e5bab64ec0' # Comics
  targetSiteId: null
  validateRelatedElements: false
  viewMode: list
translationKeyFormat: null
translationMethod: site
type: craft\fields\Assets
