columnSuffix: null
contentColumnType: string
fieldGroup: 015d48f9-dd42-4c18-b3b5-8a8f4e9106e9 # Common
handle: contactInfo
instructions: ''
name: 'Contact Info'
searchable: false
settings:
  columns:
    __assoc__:
      -
        - 2d8820e3-8e6b-4278-800c-ae4cdf640b73 # Address
        -
          __assoc__:
            -
              - width
              - ''
      -
        - c28466ca-bc45-4fb5-8097-445e3bec82e2 # Email
        -
          __assoc__:
            -
              - width
              - ''
  contentTable: '{{%stc_contactinfo}}'
  fieldLayout: row
  maxRows: ''
  minRows: ''
  placeholderKey: null
  propagationKeyFormat: null
  propagationMethod: all
  selectionLabel: ''
  staticField: '1'
translationKeyFormat: null
translationMethod: site
type: verbb\supertable\fields\SuperTableField
