columnSuffix: null
contentColumnType: string
fieldGroup: 58c2356a-6bf8-4648-ae2e-b0d45ba067f4 # Site Options
handle: contactInfo
instructions: 'Currently shows on About page using the shortcode [contact]'
name: 'Contact Info'
searchable: false
settings:
  blockTypeFields: 0
  changedFieldIndicator: null
  columns:
    __assoc__:
      -
        - 2d8820e3-8e6b-4278-800c-ae4cdf640b73 # Address
        -
          __assoc__:
            -
              - width
              - ''
      -
        - c28466ca-bc45-4fb5-8097-445e3bec82e2 # Email
        -
          __assoc__:
            -
              - width
              - ''
  contentTable: '{{%stc_contactinfo}}'
  fieldLayout: row
  maxRows: null
  minRows: null
  propagationKeyFormat: null
  propagationMethod: all
  selectionLabel: null
  staticField: true
translationKeyFormat: null
translationMethod: site
type: verbb\supertable\fields\SuperTableField
