columnSuffix: mfktklwn
contentColumnType: string
fieldGroup: 015d48f9-dd42-4c18-b3b5-8a8f4e9106e9 # Common
handle: interviews
instructions: ''
name: Interviews
searchable: false
settings:
  columns:
    __assoc__:
      -
        - 57833ca5-8ac6-4bf7-98d6-6ba454a3cea5 # Name
        -
          __assoc__:
            -
              - width
              - ''
      -
        - cf4366ab-a69e-47f1-aefe-31870e2276f3 # Date
        -
          __assoc__:
            -
              - width
              - ''
      -
        - 526177fe-7cbc-4b91-97f4-27abb175e5a8 # Interviewer
        -
          __assoc__:
            -
              - width
              - ''
      -
        - be4dcd68-2b70-42af-8608-0f946398e666 # Topics
        -
          __assoc__:
            -
              - width
              - ''
  contentTable: '{{%stc_interviews}}'
  fieldLayout: table
  maxRows: ''
  minRows: ''
  placeholderKey: null
  propagationKeyFormat: null
  propagationMethod: all
  selectionLabel: ''
  staticField: ''
translationKeyFormat: null
translationMethod: site
type: verbb\supertable\fields\SuperTableField
