columnSuffix: null
contentColumnType: string
fieldGroup: 58c2356a-6bf8-4648-ae2e-b0d45ba067f4 # Site Options
handle: socialLinks
instructions: 'Currently shows on About page using the shortcode [social-links], and hardcoded at the bottom of the Links page template'
name: 'Social Links'
searchable: false
settings:
  blockTypeFields: 0
  changedFieldIndicator: null
  columns:
    __assoc__:
      -
        - ea1e5860-b977-428c-84ec-aeede3de6781 # Title
        -
          __assoc__:
            -
              - width
              - ''
      -
        - 86f51217-15e7-43c2-a243-9df28902664b # URL
        -
          __assoc__:
            -
              - width
              - ''
      -
        - 4e24dd23-7a35-42a3-884d-8dd41fe38708 # Image
        -
          __assoc__:
            -
              - width
              - ''
  contentTable: '{{%stc_sociallinks}}'
  fieldLayout: table
  maxRows: null
  minRows: null
  propagationKeyFormat: null
  propagationMethod: all
  selectionLabel: 'Add a link'
  staticField: null
translationKeyFormat: null
translationMethod: site
type: verbb\supertable\fields\SuperTableField
