field: 3c7929de-5688-43ec-b0ca-171b2432cc83 # Contact Info
fieldLayouts:
  6906b7fa-d8f0-46ec-8f16-fbd066ac78ad:
    tabs:
      -
        elements:
          -
            fieldUid: 2d8820e3-8e6b-4278-800c-ae4cdf640b73 # Address
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: c28466ca-bc45-4fb5-8097-445e3bec82e2 # Email
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  2d8820e3-8e6b-4278-800c-ae4cdf640b73: # Address
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: address
    instructions: ''
    name: Address
    searchable: false
    settings:
      availableTransforms: '*'
      availableVolumes: '*'
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: ''
      purifyHtml: '1'
      redactorConfig: ''
      removeEmptyTags: '1'
      removeInlineStyles: '1'
      removeNbsp: '1'
      showHtmlButtonForNonAdmins: ''
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
  c28466ca-bc45-4fb5-8097-445e3bec82e2: # Email
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: email
    instructions: ''
    name: Email
    searchable: false
    settings:
      placeholder: ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Email
