changedFieldIndicator: null
field: 28bcab46-1178-4204-8587-32e4bb9e6ed2 # Bibliography
fieldLayouts:
  e36f4e8a-0cdd-4151-9fb6-0cd656677167:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 4c57db8a-2a37-4bf4-8636-62780119f7c0 # Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 44eba8d4-7dfa-4756-ba1e-d911c5f2e793
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: c5367f71-b0ec-4e4d-8813-02ce06fed536 # Release Date
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 29983560-4a78-401d-bd52-0354f45a9b87
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: f149d6a3-c80e-45dc-a138-3ad98d2f5291 # Number of Pages
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1d35c066-58a1-41a7-9289-f2517f5d023e
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 7d2158f0-f36b-4144-b226-3f765ee39d98 # Anthology / Publisher
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8e37a42a-45aa-4597-b594-52fddf0a69d4
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 7c744b27-e29f-46b4-8668-b586ee0ebd05
        userCondition: null
fields:
  4c57db8a-2a37-4bf4-8636-62780119f7c0: # Title
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: bibliographyTitle
    instructions: null
    name: Title
    searchable: false
    settings:
      availableTransforms: '*'
      availableVolumes: '*'
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: null
      purifyHtml: true
      redactorConfig: Simple.json
      removeEmptyTags: true
      removeInlineStyles: true
      removeNbsp: true
      showHtmlButtonForNonAdmins: false
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
  7d2158f0-f36b-4144-b226-3f765ee39d98: # Anthology / Publisher
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: anthologyPublisher
    instructions: null
    name: 'Anthology / Publisher'
    searchable: false
    settings:
      availableTransforms: '*'
      availableVolumes: '*'
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: null
      purifyHtml: true
      redactorConfig: Simple.json
      removeEmptyTags: true
      removeInlineStyles: true
      removeNbsp: true
      showHtmlButtonForNonAdmins: false
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
  c5367f71-b0ec-4e4d-8813-02ce06fed536: # Release Date
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: releaseDate
    instructions: null
    name: 'Release Date'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  f149d6a3-c80e-45dc-a138-3ad98d2f5291: # Number of Pages
    columnSuffix: null
    contentColumnType: integer(10)
    fieldGroup: null
    handle: numberOfPages
    instructions: null
    name: 'Number of Pages'
    searchable: false
    settings:
      decimals: 0
      defaultValue: null
      max: null
      min: 0
      prefix: null
      previewCurrency: null
      previewFormat: none
      size: null
      suffix: null
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Number
