field: 28bcab46-1178-4204-8587-32e4bb9e6ed2 # Bibliography
fieldLayouts:
  e36f4e8a-0cdd-4151-9fb6-0cd656677167:
    tabs:
      -
        elements:
          -
            fieldUid: 4c57db8a-2a37-4bf4-8636-62780119f7c0 # Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: c5367f71-b0ec-4e4d-8813-02ce06fed536 # Release Date
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: f149d6a3-c80e-45dc-a138-3ad98d2f5291 # Number of Pages
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 7d2158f0-f36b-4144-b226-3f765ee39d98 # Anthology / Publisher
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  4c57db8a-2a37-4bf4-8636-62780119f7c0: # Title
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: bibliographyTitle
    instructions: ''
    name: Title
    searchable: false
    settings:
      availableTransforms: '*'
      availableVolumes: '*'
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: ''
      purifyHtml: '1'
      redactorConfig: Simple.json
      removeEmptyTags: '1'
      removeInlineStyles: '1'
      removeNbsp: '1'
      showHtmlButtonForNonAdmins: ''
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
  7d2158f0-f36b-4144-b226-3f765ee39d98: # Anthology / Publisher
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: anthologyPublisher
    instructions: ''
    name: 'Anthology / Publisher'
    searchable: false
    settings:
      availableTransforms: '*'
      availableVolumes: '*'
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: ''
      purifyHtml: '1'
      redactorConfig: Simple.json
      removeEmptyTags: '1'
      removeInlineStyles: '1'
      removeNbsp: '1'
      showHtmlButtonForNonAdmins: ''
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
  c5367f71-b0ec-4e4d-8813-02ce06fed536: # Release Date
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: releaseDate
    instructions: ''
    name: 'Release Date'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  f149d6a3-c80e-45dc-a138-3ad98d2f5291: # Number of Pages
    columnSuffix: null
    contentColumnType: integer(10)
    fieldGroup: null
    handle: numberOfPages
    instructions: ''
    name: 'Number of Pages'
    searchable: false
    settings:
      decimals: 0
      defaultValue: null
      max: null
      min: 0
      prefix: null
      previewCurrency: ''
      previewFormat: none
      size: null
      suffix: null
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Number
