changedFieldIndicator: null
field: ce9ca5a9-7ec2-405f-a639-ab22bca77b92 # Link Blocks
fieldLayouts:
  cebe0502-226b-490e-b04e-dae25332c5c7:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 25f7071a-0510-4f79-a798-33bd9b87fc5d # Title
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 00a29376-aae8-418b-8513-c67eaa2f6c07
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 89b317b4-8edc-4c80-9477-1406a3da4165 # URL
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c5abd773-65e8-4daa-8bc4-53e4392339d6
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 526bab9f-412a-4287-899e-0ce622b373b6 # Open in New Tab
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 273e9689-418c-4f8f-823f-7e28ba575347
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: e8ce7d83-e450-4872-a359-71110fe805af # Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8286a86e-7b65-4675-b1ad-4cd470aff52e
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 228b1a99-262d-49bc-a796-5f102632eb26 # Description
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 71187cc7-2303-463c-9940-cdb22ad3455a
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 8de62344-046c-4106-b594-5610412b7099
        userCondition: null
fields:
  25f7071a-0510-4f79-a798-33bd9b87fc5d: # Title
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: linkTitle
    instructions: null
    name: Title
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  89b317b4-8edc-4c80-9477-1406a3da4165: # URL
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: linkUrl
    instructions: null
    name: URL
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: true
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: 'e.g. /relative-link/ or https://external.link'
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  228b1a99-262d-49bc-a796-5f102632eb26: # Description
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: description
    instructions: null
    name: Description
    searchable: false
    settings:
      availableTransforms: '*'
      availableVolumes: '*'
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: null
      purifyHtml: true
      redactorConfig: Simple.json
      removeEmptyTags: true
      removeInlineStyles: true
      removeNbsp: true
      showHtmlButtonForNonAdmins: false
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
  526bab9f-412a-4287-899e-0ce622b373b6: # Open in New Tab
    columnSuffix: null
    contentColumnType: boolean
    fieldGroup: null
    handle: openInNewTab
    instructions: null
    name: 'Open in New Tab'
    searchable: false
    settings:
      default: false
      offLabel: null
      onLabel: null
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Lightswitch
  e8ce7d83-e450-4872-a359-71110fe805af: # Image
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: image
    instructions: null
    name: Image
    searchable: false
    settings:
      allowSelfRelations: false
      allowSubfolders: false
      allowUploads: true
      allowedKinds: null
      branchLimit: null
      defaultUploadLocationSource: 'volume:a405f9ff-0740-4d3d-a58e-ccb58c2a8517' # General
      defaultUploadLocationSubpath: null
      localizeRelations: false
      maintainHierarchy: false
      maxRelations: 1
      minRelations: null
      previewMode: full
      restrictFiles: false
      restrictLocation: false
      restrictedDefaultUploadSubpath: null
      restrictedLocationSource: 'volume:a405f9ff-0740-4d3d-a58e-ccb58c2a8517' # General
      restrictedLocationSubpath: null
      selectionLabel: 'Add image'
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      sources: '*'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: list
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
