fieldLayouts:
  44d012cf-58a9-42bf-bd3d-fdae4bcf553f:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 3c7929de-5688-43ec-b0ca-171b2432cc83 # Contact Info
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a83f546f-3d7d-49a9-b4cf-4d04f5c63ab7
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: b9b32ab0-d5dc-4406-aa3c-51890a2f4cca # Social Links
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7f2c4e5d-0312-486a-9c92-276c5107cea6
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: e361925d-2758-43ae-af93-763708c38a12 # Share Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 28a9f7c9-4941-4b22-a952-71d5a2bde672
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 975e76ae-9f61-4063-b5c6-1c5ea2c34115 # News Per Page
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: af360768-9650-4133-8036-c7717003adf2
            userCondition: null
            warning: null
            width: 100
        name: Options
        uid: e43d94a9-8bed-4fd5-a1a4-57390724c686
        userCondition: null
handle: siteOptions
name: 'Site Options'
sortOrder: 1
