fieldLayouts:
  44d012cf-58a9-42bf-bd3d-fdae4bcf553f:
    tabs:
      -
        elements:
          -
            fieldUid: 3c7929de-5688-43ec-b0ca-171b2432cc83 # Contact Info
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: b9b32ab0-d5dc-4406-aa3c-51890a2f4cca # Social Links
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: e361925d-2758-43ae-af93-763708c38a12 # Share Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 975e76ae-9f61-4063-b5c6-1c5ea2c34115 # News Per Page
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Options
        sortOrder: 1
handle: siteOptions
name: 'Site Options'
sortOrder: 1
