defaultPlacement: end
enableVersioning: true
handle: aboutPages
name: 'About Pages'
propagationMethod: all
siteSettings:
  4baa37ad-12ad-43a8-b9da-86dc1276ac93: # A-L 6.0
    enabledByDefault: true
    hasUrls: true
    template: _page
    uriFormat: 'about/{slug}'
structure:
  maxLevels: 1
  uid: ea7b9b6f-3943-4358-bf16-abb2ba646414
type: structure
