defaultPlacement: end
enableVersioning: true
handle: comicsIndex
name: 'Comics Index'
propagationMethod: all
siteSettings:
  4baa37ad-12ad-43a8-b9da-86dc1276ac93: # A-L 6.0
    enabledByDefault: true
    hasUrls: true
    template: comics/index
    uriFormat: comics-index
type: single
