defaultPlacement: end
enableVersioning: true
handle: fourOhFour
name: '404'
propagationMethod: all
siteSettings:
  4baa37ad-12ad-43a8-b9da-86dc1276ac93: # Alec Longstreth
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
type: single
