defaultPlacement: end
enableVersioning: true
handle: homepage
name: Homepage
propagationMethod: all
siteSettings:
  4baa37ad-12ad-43a8-b9da-86dc1276ac93: # A-L 2.0
    enabledByDefault: true
    hasUrls: true
    template: index
    uriFormat: __home__
type: single
