defaultPlacement: end
enableVersioning: true
handle: interviews
name: Interviews
propagationMethod: all
siteSettings:
  4baa37ad-12ad-43a8-b9da-86dc1276ac93: # Alec Longstreth
    enabledByDefault: true
    hasUrls: true
    template: links/_interviews
    uriFormat: links/interviews
type: single
