defaultPlacement: end
enableVersioning: true
handle: links
name: Links
propagationMethod: all
siteSettings:
  4baa37ad-12ad-43a8-b9da-86dc1276ac93: # A-L 6.0
    enabledByDefault: true
    hasUrls: true
    template: links/index
    uriFormat: links
type: single
